version: "3.8"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_sportdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sport_backend_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Database=sportdb;Username=postgres;Password=postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sport_frontend_app
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  pgdata:
